### ISSUE TITLE
Error running td3_train

### ISSUE THREAD

**Issue by ethompson93** [scil-vital/TrackToLearn#11]
Hi Antoine,

I've been trying to run Track-to-learn, starting out with the fibre cup data you provided on zenodo (Thank you for making this code and dataset available!). I'm getting the following error message when I try to train the agent:

`  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "TrackToLearn/runners/td3_train.py", line 374, in <module>
    main()
  File "TrackToLearn/runners/td3_train.py", line 370, in main
    td3_experiment.run()
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/runners/train.py", line 338, in run
    self.rl_train(alg, env, back_env, test_env, back_test_env)
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/runners/train.py", line 238, in rl_train
    alg, test_env, back_test_env)
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/runners/ttl.py", line 565, in test
    back_env)
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/algorithms/rl.py", line 191, in run_validation
    batch_size, env, backward_env, compress
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/algorithms/rl.py", line 154, in generate_streamlines
    and compress)
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/algorithms/rl.py", line 119, in _validation_episode
    next_state, h)
  File "/home/ethompso/scripts/TracktoLearn/TrackToLearn/TrackToLearn/environments/tracker.py", line 251, in harvest
    hidden)
TypeError: _keep() takes 3 positional arguments but 4 were given`

Do you know what might be causing this? I'm using a script based on one you posted in a previous issue: [run_training.qsub.txt](https://github.com/scil-vital/TrackToLearn/files/11343506/run_training.qsub.txt)

Thanks in advance for any help you are able to provide,

Ellie

**Comment by AntoineTheb** [comment]
Hi ! Thank you for your interest in Track-to-Learn ! 

I will take a look at the issue today and report back with a patch or a solution as soon as possible.

**Comment by AntoineTheb** [comment]
Hello again @ethompson93 !

I have provided a fix in #12 , and merged the pull request. I have run the script you provided for 50 epochs, everything seems to work now.

Let me know if you still encounter bugs, or if you would like more info on the framework ! Also, in the coming weeks, I will be updating this repository to include recent works in updating and testing this framework. Stay tuned !

**Comment by ethompson93** [comment]
Amazing, thank you so much for such a speedy response! Looking forward to seeing the updates
